### ISSUE TITLE
Can you please provide a example folder with a html demo

### ISSUE THREAD

**Issue by martinberlin** [dfrankland/wasm-brotli#4]
I really like this idea and I would like to try it out. So far we where compressing Brotli using nodejs in the backend, but if this works, it would be great to use it in a Chromeapp.
It would be possible that you can provide a full example to see how this runs in the client side?
Like a test.html including your script and encoding a simple "string" in the Browser

Sorry if it's not the place to ask, but I was trying to get this too work in the client side and I still could not.

**Comment by dfrankland** [comment]
Hey, thanks for asking! I just went through and updated everything as well as creating an example over on Codesandbox:
https://codesandbox.io/s/wasm-brotli-example-uzpt5?fontsize=14

**Comment by martinberlin** [comment]
Great, will try very soon. So far just open your link from the iPad. I don’t think web assembly works in Chrome on devices it will be nice to try (in android did not work in my first tries)
![3D3BD5E1-B80E-406A-86BC-C908D5AAE794](https://user-images.githubusercontent.com/2692928/68615573-9dc09800-04c3-11ea-82eb-0c0f64dcdcc9.png)

**Comment by dfrankland** [comment]
That error displayed is a problem with file upload. I tested this on my Android phone and everything worked. I assume Safari (and Chrome for iOS by extension) probably doesn't support some of the file upload code I wrote.

**Comment by dfrankland** [comment]
I swapped out [`Blob.arrayBuffer()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer) for [`FileReader`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) and I was able to successfully use the example on Safari on macOS. Please try the example again, if you don't mind :smile:

**Comment by martinberlin** [comment]
Great now it works!   Thanks a lot for the example.
Didn't knew this codesandbox.io it looks amazing to build test tools. Thanks for building this will try to compare speeds with the one I'm using: https://github.com/phiresky/rust-brotli-wasm  (brotli-wasm-bindgen version)
I'm compressing RGB byte information here http://udpx.fasani.de before sending it via WiFi to an ESP32 chip to controll addressable Leds. You may like this project too ;)
Thanks Dylan

**Comment by dfrankland** [comment]
Looks like the example works 👍 closing for now
